### ISSUE TITLE
`random seed` error in native.rb

### ISSUE THREAD

**Issue by mattieb** [igrigorik/bloomfilter-rb#33]
I have this library as a dependency of `twitter_ebooks`, where I opened mispy/twitter_ebooks#10.

I have the library compiled on OpenBSD, and occasionally get this traceback:

```
/home/ebooks/zigg_ebooks/vendor/bundle/ruby/1.9.1/gems/bloomfilter-rb-2.1.1/lib/bloomfilter/native.rb:20:in `new': random seed (ArgumentError)
        from /home/ebooks/zigg_ebooks/vendor/bundle/ruby/1.9.1/gems/bloomfilter-rb-2.1.1/lib/bloomfilter/native.rb:20:in `initialize'
…
```

I think I am working around the issue by adding `% 65536` to the `:seed` value.  But I'm not totally confident that's the issue.

A quick `sizeof` test says `int` (cf. https://github.com/igrigorik/bloomfilter-rb/blob/master/ext/cbloomfilter/cbloomfilter.c#L20) is 4 bytes on OpenBSD, so it seems like it should fit, but something's not working right here since at some point `s` becomes `< 0`, apparently.

**Comment by mdhausman** [comment]
I'm getting this issue as well with a RasPi running Debian (Jessie)

**Comment by igrigorik** [comment]
@mdhausman which Ruby version? The problem is that I can't reproduce it on this end.. :(

**Comment by mdhausman** [comment]
```sh
$ ruby --version
ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabihf]
```
