### ISSUE TITLE
Publish 2.1.2 to RubyGems

### ISSUE THREAD

**Issue by abhishekwearisma** [igrigorik/bloomfilter-rb#47]
`2.1.1` -> `2.1.2` has a fix that is really nice to have. The `bitmap` and `load` functions pack tighter bitmaps. I noticed that RubyGems only has `2.1.1`, and so I'm having to build `2.1.2` from source. Any chance `2.1.2` can be published as well?

**Comment by igrigorik** [comment]
Thanks for the nudge! 2.1.2 should be live on rubygems.
