### ISSUE TITLE
Compatibility Inquiry: bloomfilter-rb 2.1.2 with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [igrigorik/bloomfilter-rb#49]
Hi,

I'm seeking confirmation regarding the compatibility of the bloomfilter-rb 2.1.2  with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems mentioned it only specifies a minimum required Ruby version of > 0. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by igrigorik** [comment]
Should work! If you encounter issues, please open a ticket.

**Comment by sydverisk** [comment]
Thanks for the update and I appreciate it!
